[font]
size = 13.0

[font.normal]
family = "0xProtoNerdFont" 
style = "Regular"

[font.bold]
family = "0xProtoNerdFont" 
style = "Bold"

[font.italic]
family = "0xProtoNerdFont" 
style = "Italic"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/tokyo-night.toml"
  # "~/.config/alacritty/tokyo-night-storm.toml"
]
